# Generated by Django 4.2.30 on 2026-07-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="标题")),
                ("goal", models.TextField(blank=True, verbose_name="学习目标")),
                ("scope", models.TextField(blank=True, verbose_name="学习范围")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("learning", "学习中"),
                            ("exam_ready", "待考试"),
                            ("reviewing", "复习中"),
                            ("archived", "已归档"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "mastery_level",
                    models.CharField(
                        choices=[
                            ("unknown", "未知"),
                            ("weak", "薄弱"),
                            ("pass", "掌握"),
                            ("strong", "熟练"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="掌握程度",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "学习主题",
                "verbose_name_plural": "学习主题",
                "ordering": ["-updated_at"],
            },
        ),
    ]
