# Generated by Django 4.2.30 on 2026-07-31 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("url", "网页链接"), ("text", "纯文本")],
                        max_length=10,
                        verbose_name="类型",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="来源URL"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="标题")),
                ("raw_text", models.TextField(blank=True, verbose_name="原始文本")),
                ("clean_text", models.TextField(blank=True, verbose_name="清洗后文本")),
                (
                    "import_status",
                    models.CharField(
                        choices=[
                            ("pending", "处理中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="导入状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="api.topic",
                        verbose_name="所属主题",
                    ),
                ),
            ],
            options={
                "verbose_name": "学习材料",
                "verbose_name_plural": "学习材料",
            },
        ),
        migrations.CreateModel(
            name="MaterialChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_index", models.IntegerField(verbose_name="片段索引")),
                ("content", models.TextField(verbose_name="片段内容")),
                ("start_offset", models.IntegerField(verbose_name="起始偏移")),
                ("end_offset", models.IntegerField(verbose_name="结束偏移")),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="api.material",
                        verbose_name="所属材料",
                    ),
                ),
            ],
            options={
                "verbose_name": "材料片段",
                "verbose_name_plural": "材料片段",
                "ordering": ["chunk_index"],
            },
        ),
    ]
