# Generated by Django 4.2.30 on 2026-07-31 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_material_materialchunk"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_text",
                    models.TextField(blank=True, verbose_name="选中文本"),
                ),
                ("question_text", models.TextField(verbose_name="问题内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提问时间"),
                ),
                (
                    "chunk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="api.materialchunk",
                        verbose_name="关联片段",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="api.material",
                        verbose_name="关联材料",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="api.topic",
                        verbose_name="所属主题",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户问题",
                "verbose_name_plural": "用户问题",
            },
        ),
        migrations.CreateModel(
            name="AIResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("briefing", "阅读前导"),
                            ("answer_question", "回答问题"),
                            ("draft_note", "笔记草稿"),
                            ("generate_exam", "生成考题"),
                            ("grade_exam", "阅卷评分"),
                        ],
                        max_length=20,
                        verbose_name="任务类型",
                    ),
                ),
                (
                    "prompt_version",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Prompt版本"
                    ),
                ),
                ("content", models.TextField(verbose_name="回答内容")),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="使用模型"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="生成时间"),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_responses",
                        to="api.material",
                        verbose_name="关联材料",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_responses",
                        to="api.question",
                        verbose_name="关联问题",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI响应",
                "verbose_name_plural": "AI响应",
            },
        ),
    ]
