# Generated by Django 4.2.30 on 2026-07-31 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_question_airesponse"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[("topic", "主题综合测验")],
                        default="topic",
                        max_length=20,
                        verbose_name="考试类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "待作答"),
                            ("submitted", "已提交"),
                            ("graded", "已评分"),
                            ("failed", "生成或评分失败"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="得分"
                    ),
                ),
                ("feedback", models.TextField(blank=True, verbose_name="总体反馈")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="提交时间"
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="api.topic",
                        verbose_name="所属主题",
                    ),
                ),
            ],
            options={
                "verbose_name": "考试",
                "verbose_name_plural": "考试",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "due_at",
                    models.DateTimeField(db_index=True, verbose_name="应复习时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[("pending", "待复习"), ("completed", "已完成")],
                        default="pending",
                        max_length=20,
                        verbose_name="结果",
                    ),
                ),
                (
                    "next_due_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="下次复习时间"
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_records",
                        to="api.exam",
                        verbose_name="关联考试",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_records",
                        to="api.topic",
                        verbose_name="所属主题",
                    ),
                ),
            ],
            options={
                "verbose_name": "复习记录",
                "verbose_name_plural": "复习记录",
                "ordering": ["due_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        default="transfer", max_length=50, verbose_name="题目类型"
                    ),
                ),
                ("scenario", models.TextField(blank=True, verbose_name="迁移场景")),
                ("question_text", models.TextField(verbose_name="题目内容")),
                (
                    "rubric_json",
                    models.JSONField(blank=True, default=dict, verbose_name="评分标准"),
                ),
                ("answer_text", models.TextField(blank=True, verbose_name="用户作答")),
                ("feedback", models.TextField(blank=True, verbose_name="评分反馈")),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="得分"
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="api.exam",
                        verbose_name="所属考试",
                    ),
                ),
            ],
            options={
                "verbose_name": "考试题目",
                "verbose_name_plural": "考试题目",
                "ordering": ["id"],
            },
        ),
    ]
