# Generated by Django 4.2.30 on 2026-07-31 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_exam_reviewrecord_examquestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="AITask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("briefing", "阅读前导"),
                            ("answer_question", "回答问题"),
                            ("generate_exam", "生成考题"),
                            ("grade_exam", "阅卷评分"),
                            ("note_draft", "笔记草稿"),
                        ],
                        max_length=30,
                        verbose_name="任务类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待执行"),
                            ("running", "执行中"),
                            ("succeeded", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "input_json",
                    models.JSONField(blank=True, default=dict, verbose_name="任务输入"),
                ),
                (
                    "result_json",
                    models.JSONField(blank=True, default=dict, verbose_name="任务结果"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "attempt_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="已尝试次数"
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="最大尝试次数"
                    ),
                ),
                (
                    "next_run_at",
                    models.DateTimeField(db_index=True, verbose_name="下次执行时间"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="使用模型"
                    ),
                ),
                (
                    "prompt_version",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Prompt版本"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_tasks",
                        to="api.exam",
                        verbose_name="关联考试",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_tasks",
                        to="api.material",
                        verbose_name="关联材料",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_tasks",
                        to="api.question",
                        verbose_name="关联问题",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_tasks",
                        to="api.topic",
                        verbose_name="关联主题",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI任务",
                "verbose_name_plural": "AI任务",
                "ordering": ["-created_at"],
            },
        ),
    ]
