# Generated by Django 4.2.30 on 2026-08-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="material_fingerprint",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, verbose_name="材料指纹"
            ),
        ),
    ]
