# Generated by Django 4.2.30 on 2026-08-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_note_material_fingerprint"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewrecord",
            name="review_prompt",
            field=models.TextField(blank=True, verbose_name="复习提示"),
        ),
        migrations.AddField(
            model_name="reviewrecord",
            name="review_prompt_generated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="复习提示生成时间"
            ),
        ),
        migrations.AddField(
            model_name="aitask",
            name="review",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_tasks",
                to="api.reviewrecord",
                verbose_name="关联复习记录",
            ),
        ),
    ]
