# Generated by Django 4.2.30 on 2026-08-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_review_prompt_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aitask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("briefing", "阅读前导"),
                    ("answer_question", "回答问题"),
                    ("generate_exam", "生成考题"),
                    ("grade_exam", "阅卷评分"),
                    ("note_draft", "笔记草稿"),
                    ("review_prompt", "复习提示"),
                ],
                max_length=30,
                verbose_name="任务类型",
            ),
        ),
    ]
