# Generated by Django 4.2.30 on 2026-08-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_aitask_task_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="source_type",
            field=models.CharField(
                choices=[("manual", "人工添加"), ("ai_recommended", "AI 推荐")],
                db_index=True,
                default="manual",
                max_length=20,
                verbose_name="来源类型",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="type",
            field=models.CharField(
                choices=[("learning", "学习"), ("discussion", "讨论")],
                db_index=True,
                default="learning",
                max_length=20,
                verbose_name="话题类型",
            ),
        ),
    ]
