# Generated by Django 4.2.30 on 2026-08-01 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_material_source_type_topic_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Concept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="概念名称")),
                ("definition", models.TextField(blank=True, verbose_name="定义")),
                ("principle", models.TextField(blank=True, verbose_name="原理")),
                ("pitfalls", models.TextField(blank=True, verbose_name="易错点")),
                ("applications", models.TextField(blank=True, verbose_name="适用场景")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "草稿"), ("confirmed", "已确认")],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "source_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_concepts",
                        to="api.aitask",
                        verbose_name="来源任务",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concepts",
                        to="api.topic",
                        verbose_name="所属主题",
                    ),
                ),
            ],
            options={
                "verbose_name": "概念卡片",
                "verbose_name_plural": "概念卡片",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Highlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_text", models.TextField(verbose_name="高亮文本")),
                ("start_offset", models.PositiveIntegerField(verbose_name="起始偏移")),
                ("end_offset", models.PositiveIntegerField(verbose_name="结束偏移")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "chunk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="highlights",
                        to="api.materialchunk",
                        verbose_name="来源片段",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlights",
                        to="api.material",
                        verbose_name="来源材料",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlights",
                        to="api.topic",
                        verbose_name="所属主题",
                    ),
                ),
            ],
            options={
                "verbose_name": "高亮",
                "verbose_name_plural": "高亮",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConceptAnchor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_text", models.TextField(verbose_name="来源文本")),
                ("start_offset", models.PositiveIntegerField(verbose_name="起始偏移")),
                ("end_offset", models.PositiveIntegerField(verbose_name="结束偏移")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "chunk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="concept_anchors",
                        to="api.materialchunk",
                        verbose_name="来源片段",
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anchors",
                        to="api.concept",
                        verbose_name="所属概念",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concept_anchors",
                        to="api.material",
                        verbose_name="来源材料",
                    ),
                ),
            ],
            options={
                "verbose_name": "概念来源锚点",
                "verbose_name_plural": "概念来源锚点",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="aitask",
            name="concept",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_tasks",
                to="api.concept",
                verbose_name="关联概念",
            ),
        ),
        migrations.AddConstraint(
            model_name="highlight",
            constraint=models.UniqueConstraint(
                fields=("material", "start_offset", "end_offset"),
                name="unique_highlight_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="conceptanchor",
            constraint=models.UniqueConstraint(
                fields=("concept", "material", "start_offset", "end_offset"),
                name="unique_concept_anchor_range",
            ),
        ),
    ]
