# Generated by Django 4.2.30 on 2026-08-01 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_aitask_task_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="concept",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="api.concept",
                verbose_name="关联概念",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="end_offset",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="结束偏移"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="is_saved",
            field=models.BooleanField(default=False, verbose_name="已沉淀"),
        ),
        migrations.AddField(
            model_name="question",
            name="saved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="沉淀时间"),
        ),
        migrations.AddField(
            model_name="question",
            name="start_offset",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="起始偏移"
            ),
        ),
    ]
