# Generated by Django 4.2.30 on 2026-08-01 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_question_concept_question_end_offset_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        default="关联", max_length=100, verbose_name="关系类型"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="关系说明")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "from_concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relations",
                        to="api.concept",
                        verbose_name="起始概念",
                    ),
                ),
                (
                    "to_concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relations",
                        to="api.concept",
                        verbose_name="目标概念",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concept_relations",
                        to="api.topic",
                        verbose_name="所属主题",
                    ),
                ),
            ],
            options={
                "verbose_name": "概念关系",
                "verbose_name_plural": "概念关系",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="conceptrelation",
            constraint=models.UniqueConstraint(
                fields=("from_concept", "to_concept"),
                name="unique_concept_relation_direction",
            ),
        ),
    ]
