# Generated by Django 4.2.30 on 2026-08-01 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_conceptrelation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="discussion_outcome",
            field=models.CharField(
                choices=[
                    ("pending", "待定"),
                    ("learn", "学习"),
                    ("not_learn", "暂不学习"),
                ],
                default="pending",
                max_length=20,
                verbose_name="讨论结论",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="discussion_rationale",
            field=models.TextField(blank=True, verbose_name="判断依据"),
        ),
        migrations.AlterField(
            model_name="aitask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("briefing", "阅读前导"),
                    ("answer_question", "回答问题"),
                    ("concept_draft", "概念草稿"),
                    ("generate_exam", "生成考题"),
                    ("grade_exam", "阅卷评分"),
                    ("note_draft", "笔记草稿"),
                    ("review_prompt", "复习提示"),
                    ("discussion_opening", "讨论开场"),
                    ("discussion_assessment", "快速评估"),
                    ("discussion_reply", "讨论回复"),
                    ("learning_path", "学习路线"),
                ],
                max_length=30,
                verbose_name="任务类型",
            ),
        ),
        migrations.CreateModel(
            name="DiscussionMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "用户"), ("assistant", "AI 助手")],
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("opening", "主动开场"),
                            ("assessment", "快速评估"),
                            ("discussion", "讨论"),
                            ("learning_path", "学习路线"),
                        ],
                        default="discussion",
                        max_length=30,
                        verbose_name="消息类型",
                    ),
                ),
                ("content", models.TextField(verbose_name="消息内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "source_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_discussion_messages",
                        to="api.aitask",
                        verbose_name="来源任务",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discussion_messages",
                        to="api.topic",
                        verbose_name="所属主题",
                    ),
                ),
            ],
            options={
                "verbose_name": "讨论消息",
                "verbose_name_plural": "讨论消息",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="aitask",
            name="discussion_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_tasks",
                to="api.discussionmessage",
                verbose_name="关联讨论消息",
            ),
        ),
    ]
