# Generated by Django 4.2.30 on 2026-08-01 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_topic_discussion_outcome_topic_discussion_rationale_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewrecord",
            name="feedback",
            field=models.TextField(blank=True, verbose_name="复盘反馈"),
        ),
        migrations.AddField(
            model_name="reviewrecord",
            name="graded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="反馈生成时间"
            ),
        ),
        migrations.AddField(
            model_name="reviewrecord",
            name="previous_review",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="follow_up_reviews",
                to="api.reviewrecord",
                verbose_name="上一轮复习",
            ),
        ),
        migrations.AddField(
            model_name="reviewrecord",
            name="response_text",
            field=models.TextField(blank=True, verbose_name="复盘回答"),
        ),
        migrations.AddField(
            model_name="reviewrecord",
            name="score",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="复盘得分"
            ),
        ),
        migrations.AlterField(
            model_name="aitask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("briefing", "阅读前导"),
                    ("answer_question", "回答问题"),
                    ("concept_draft", "概念草稿"),
                    ("generate_exam", "生成考题"),
                    ("grade_exam", "阅卷评分"),
                    ("note_draft", "笔记草稿"),
                    ("review_prompt", "复习提示"),
                    ("grade_review", "复盘反馈"),
                    ("discussion_opening", "讨论开场"),
                    ("discussion_assessment", "快速评估"),
                    ("discussion_reply", "讨论回复"),
                    ("learning_path", "学习路线"),
                ],
                max_length=30,
                verbose_name="任务类型",
            ),
        ),
    ]
