# Generated by Django 4.2.30 on 2026-08-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_reviewrecord_feedback_reviewrecord_graded_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="highlight",
            name="user_note",
            field=models.TextField(blank=True, verbose_name="用户备注"),
        ),
    ]
