# Generated by Django 4.2.30 on 2026-08-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_highlight_user_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airesponse",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("briefing", "阅读前导"),
                    ("answer_question", "回答问题"),
                    ("generate_exam", "生成考题"),
                    ("grade_exam", "阅卷评分"),
                ],
                max_length=20,
                verbose_name="任务类型",
            ),
        ),
        migrations.AlterField(
            model_name="aitask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("briefing", "阅读前导"),
                    ("answer_question", "回答问题"),
                    ("concept_draft", "概念草稿"),
                    ("generate_exam", "生成考题"),
                    ("grade_exam", "阅卷评分"),
                    ("review_prompt", "复习提示"),
                    ("grade_review", "复盘反馈"),
                    ("discussion_opening", "讨论开场"),
                    ("discussion_assessment", "快速评估"),
                    ("discussion_reply", "讨论回复"),
                    ("learning_path", "学习路线"),
                ],
                max_length=30,
                verbose_name="任务类型",
            ),
        ),
        migrations.DeleteModel(
            name="Note",
        ),
    ]
