# Generated by Django 4.2.30 on 2026-08-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_alter_airesponse_task_type_alter_aitask_task_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aitask",
            name="priority",
            field=models.IntegerField(db_index=True, default=0, verbose_name="优先级"),
        ),
        migrations.AddField(
            model_name="discussionmessage",
            name="stage_suggestion_reason",
            field=models.TextField(blank=True, verbose_name="阶段建议理由"),
        ),
        migrations.AddField(
            model_name="discussionmessage",
            name="suggested_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("explore", "探索"),
                    ("frame", "定义问题"),
                    ("decide", "形成决策"),
                ],
                max_length=20,
                null=True,
                verbose_name="建议讨论阶段",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="discussion_context",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="讨论工作记忆"
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="discussion_stage",
            field=models.CharField(
                choices=[
                    ("explore", "探索"),
                    ("frame", "定义问题"),
                    ("decide", "形成决策"),
                ],
                default="explore",
                max_length=20,
                verbose_name="讨论阶段",
            ),
        ),
    ]
