# Generated by Django 4.2.30 on 2026-08-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_aitask_priority_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="import_error",
            field=models.TextField(blank=True, verbose_name="导入失败原因"),
        ),
    ]
