# Generated by Django 4.2.30 on 2026-08-04 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_material_import_error"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(blank=True, verbose_name="系统提示词"),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="使用模型"
                    ),
                ),
                (
                    "session_scene",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="会话场景"
                    ),
                ),
                (
                    "context_msg",
                    models.TextField(blank=True, verbose_name="压缩上下文"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "会话",
                "verbose_name_plural": "会话",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="aitask",
            name="trigger_id",
            field=models.PositiveBigIntegerField(
                blank=True, db_index=True, null=True, verbose_name="触发方ID"
            ),
        ),
        migrations.AddField(
            model_name="aitask",
            name="trigger_type",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, verbose_name="触发方类型"
            ),
        ),
        migrations.AddField(
            model_name="conceptrelation",
            name="from_topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="outgoing_concept_relations",
                to="api.topic",
                verbose_name="起始概念所属主题",
            ),
        ),
        migrations.AddField(
            model_name="conceptrelation",
            name="to_topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incoming_concept_relations",
                to="api.topic",
                verbose_name="目标概念所属主题",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="created_by",
            field=models.CharField(
                choices=[("manual", "人工添加"), ("ai_recommended", "AI 推荐")],
                default="manual",
                max_length=20,
                verbose_name="首次创建来源",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="digest",
            field=models.TextField(blank=True, verbose_name="材料摘要"),
        ),
        migrations.AddField(
            model_name="material",
            name="error",
            field=models.TextField(blank=True, verbose_name="V2处理错误"),
        ),
        migrations.AddField(
            model_name="material",
            name="media_meta",
            field=models.JSONField(blank=True, default=dict, verbose_name="媒体元信息"),
        ),
        migrations.AddField(
            model_name="material",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("text", "纯文本"),
                    ("web_page", "网页"),
                    ("video", "视频"),
                    ("audio", "音频"),
                ],
                db_index=True,
                default="text",
                max_length=20,
                verbose_name="媒体类型",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="media_uri",
            field=models.CharField(
                blank=True, max_length=1000, verbose_name="媒体引用"
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "处理中"),
                    ("playable", "可播放"),
                    ("ready", "可学习"),
                    ("failed", "失败"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="V2处理状态",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AddField(
            model_name="materialchunk",
            name="end_time",
            field=models.FloatField(
                blank=True, null=True, verbose_name="媒体结束时间（秒）"
            ),
        ),
        migrations.AddField(
            model_name="materialchunk",
            name="start_time",
            field=models.FloatField(
                blank=True, null=True, verbose_name="媒体起始时间（秒）"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="conclusion",
            field=models.TextField(blank=True, verbose_name="问答结论"),
        ),
        migrations.AddField(
            model_name="question",
            name="status",
            field=models.CharField(
                choices=[("open", "开放"), ("closed", "已关闭")],
                default="open",
                max_length=20,
                verbose_name="V2状态",
            ),
        ),
        migrations.AlterField(
            model_name="aitask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("briefing", "阅读前导"),
                    ("answer_question", "回答问题"),
                    ("concept_draft", "概念草稿"),
                    ("generate_exam", "生成考题"),
                    ("grade_exam", "阅卷评分"),
                    ("review_prompt", "复习提示"),
                    ("grade_review", "复盘反馈"),
                    ("discussion_opening", "讨论开场"),
                    ("discussion_assessment", "快速评估"),
                    ("discussion_reply", "讨论回复"),
                    ("learning_path", "学习路线"),
                    ("asr", "视频转录"),
                    ("scrape", "网页抓取"),
                    ("digest", "生成摘要"),
                    ("concept_extract", "概念提取"),
                    ("supplement_search", "补充资料检索"),
                ],
                max_length=30,
                verbose_name="任务类型",
            ),
        ),
        migrations.CreateModel(
            name="TopicMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "import_by",
                    models.CharField(
                        choices=[("manual", "人工添加"), ("ai_recommended", "AI 推荐")],
                        default="manual",
                        max_length=20,
                        verbose_name="关联方式",
                    ),
                ),
                (
                    "import_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="关联时间"),
                ),
                (
                    "import_reason",
                    models.TextField(blank=True, verbose_name="导入理由"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("exam_material", "考试材料"),
                            ("recommended_reading", "推荐阅读"),
                        ],
                        default="recommended_reading",
                        max_length=30,
                        verbose_name="材料分类",
                    ),
                ),
                (
                    "relevance_score",
                    models.FloatField(blank=True, null=True, verbose_name="主题相关度"),
                ),
                (
                    "removed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="从当前主题移除时间"
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_materials",
                        to="api.material",
                        verbose_name="关联材料",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_materials",
                        to="api.topic",
                        verbose_name="所属主题",
                    ),
                ),
            ],
            options={
                "verbose_name": "主题材料关联",
                "verbose_name_plural": "主题材料关联",
            },
        ),
        migrations.CreateModel(
            name="SessionMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "msg_from",
                    models.CharField(
                        choices=[("user", "用户"), ("ai", "AI")],
                        max_length=10,
                        verbose_name="消息来源",
                    ),
                ),
                ("msg_content", models.TextField(verbose_name="消息内容")),
                (
                    "msg_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="消息时间"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="api.session",
                        verbose_name="所属会话",
                    ),
                ),
            ],
            options={
                "verbose_name": "会话消息",
                "verbose_name_plural": "会话消息",
                "ordering": ["msg_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="session",
            name="context_material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="api.material",
                verbose_name="上下文材料",
            ),
        ),
        migrations.CreateModel(
            name="MaterialTextLocator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_text", models.TextField(verbose_name="来源文本")),
                (
                    "start_offset",
                    models.PositiveIntegerField(verbose_name="文本起始偏移"),
                ),
                (
                    "end_offset",
                    models.PositiveIntegerField(verbose_name="文本结束偏移"),
                ),
                (
                    "time_start_offset",
                    models.FloatField(
                        blank=True, null=True, verbose_name="媒体起始时间（秒）"
                    ),
                ),
                (
                    "time_end_offset",
                    models.FloatField(
                        blank=True, null=True, verbose_name="媒体结束时间（秒）"
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("concept", "概念"),
                            ("highlight", "高亮"),
                            ("question", "问题"),
                        ],
                        max_length=20,
                        verbose_name="实体类型",
                    ),
                ),
                ("entity_id", models.PositiveBigIntegerField(verbose_name="实体ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "chunk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="text_locators",
                        to="api.materialchunk",
                        verbose_name="关联片段",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_locators",
                        to="api.material",
                        verbose_name="关联材料",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_locators",
                        to="api.topic",
                        verbose_name="创建主题",
                    ),
                ),
            ],
            options={
                "verbose_name": "材料文本定位器",
                "verbose_name_plural": "材料文本定位器",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="api.session",
                verbose_name="所属会话",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discussion_topics",
                to="api.session",
                verbose_name="讨论会话",
            ),
        ),
        migrations.AddConstraint(
            model_name="topicmaterial",
            constraint=models.UniqueConstraint(
                fields=("topic", "material"), name="unique_topic_material"
            ),
        ),
        migrations.AddIndex(
            model_name="materialtextlocator",
            index=models.Index(
                fields=["entity_type", "entity_id"], name="locator_entity_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialtextlocator",
            index=models.Index(
                fields=["material", "time_start_offset"], name="locator_timeline_idx"
            ),
        ),
    ]
