# Generated by Django 4.2.30 on 2026-08-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0022_migrate_v1_data_to_v2_core"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="type",
            field=models.CharField(
                choices=[
                    ("url", "网页链接"),
                    ("text", "纯文本"),
                    ("video", "本地视频"),
                ],
                max_length=10,
                verbose_name="类型",
            ),
        ),
    ]
