# Generated by Django 4.2.30 on 2026-08-06 15:11

import django.db.models.deletion
from django.db import migrations, models


def migrate_topic_discussions(apps, schema_editor):
    session = apps.get_model("api", "Session")
    ai_task = apps.get_model("api", "AITask")
    session.objects.filter(session_scene="discussion").update(
        session_scene="topic_discussion"
    )
    ai_task.objects.filter(
        task_type__in=(
            "discussion_opening",
            "discussion_assessment",
            "learning_path",
        ),
        status__in=("pending", "running"),
    ).update(status="cancelled", error_message="旧话题讨论流程已停用")


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0028_alter_material_status"),
    ]

    operations = [
        migrations.RunPython(migrate_topic_discussions, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="topic",
            name="discussion_context",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="discussion_outcome",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="discussion_rationale",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="discussion_stage",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="type",
        ),
        migrations.AlterField(
            model_name="aitask",
            name="task_type",
            field=models.CharField(
                db_index=True, max_length=50, verbose_name="任务类型"
            ),
        ),
        migrations.CreateModel(
            name="MaterialRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="标题")),
                ("url", models.URLField(max_length=1000, verbose_name="来源链接")),
                (
                    "content_snapshot",
                    models.TextField(blank=True, verbose_name="正文快照"),
                ),
                (
                    "content_md5",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("exam_material", "考试材料"),
                            ("recommended_reading", "推荐阅读"),
                        ],
                        default="recommended_reading",
                        max_length=30,
                        verbose_name="材料分类",
                    ),
                ),
                ("relevance_score", models.FloatField(verbose_name="主题相关度")),
                ("reason", models.TextField(blank=True, verbose_name="推荐理由")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待采纳"),
                            ("adopted", "已采纳"),
                            ("dismissed", "已忽略"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="采纳状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="推荐时间"),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="处理时间"
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="api.material",
                        verbose_name="采纳材料",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_recommendations",
                        to="api.sessionmessage",
                        verbose_name="关联回复",
                    ),
                ),
                (
                    "source_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_recommendations",
                        to="api.aitask",
                        verbose_name="来源任务",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_recommendations",
                        to="api.topic",
                        verbose_name="所属主题",
                    ),
                ),
            ],
            options={
                "verbose_name": "材料推荐",
                "verbose_name_plural": "材料推荐",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="materialrecommendation",
            constraint=models.UniqueConstraint(
                fields=("topic", "url"), name="unique_topic_recommendation_url"
            ),
        ),
    ]
