# Generated by Django 4.2.30 on 2026-08-07 01:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0029_unify_topic_and_material_recommendations"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "singleton_id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "llm_provider_type",
                    models.CharField(
                        choices=[("ollama", "Ollama"), ("openai", "OpenAI 兼容服务")],
                        default="ollama",
                        max_length=20,
                    ),
                ),
                ("llm_base_url", models.URLField(default="http://localhost:11434/v1")),
                (
                    "llm_api_key",
                    models.CharField(blank=True, default="ollama", max_length=500),
                ),
                (
                    "llm_model",
                    models.CharField(default="qwen3.6:35b-a3b", max_length=100),
                ),
                (
                    "llm_model_topic_chat",
                    models.CharField(default="qwen3:30b-a3b", max_length=100),
                ),
                (
                    "llm_model_supplement_query",
                    models.CharField(default="qwen3:30b-a3b", max_length=100),
                ),
                (
                    "llm_model_supplement_evaluate",
                    models.CharField(default="qwen3.6:35b-a3b", max_length=100),
                ),
                (
                    "llm_model_briefing",
                    models.CharField(default="qwen3:30b-a3b", max_length=100),
                ),
                (
                    "llm_model_clean_text",
                    models.CharField(default="qwen3.6:35b-a3b", max_length=100),
                ),
                (
                    "llm_model_answer_question",
                    models.CharField(default="qwen3.6:35b-a3b", max_length=100),
                ),
                (
                    "llm_model_concept_draft",
                    models.CharField(default="qwen3.6:35b-a3b", max_length=100),
                ),
                (
                    "llm_model_generate_exam",
                    models.CharField(default="qwen3.6:35b-a3b", max_length=100),
                ),
                (
                    "llm_model_grade_exam",
                    models.CharField(default="qwen3.6:35b-a3b", max_length=100),
                ),
                (
                    "llm_model_review_prompt",
                    models.CharField(default="qwen3:30b-a3b", max_length=100),
                ),
                (
                    "llm_model_grade_review",
                    models.CharField(default="qwen3.6:35b-a3b", max_length=100),
                ),
                (
                    "ollama_keep_alive",
                    models.CharField(blank=True, default="2m", max_length=30),
                ),
                ("asr_model", models.CharField(default="small", max_length=100)),
                (
                    "tts_voices",
                    models.TextField(
                        default="zh-CN-XiaoxiaoNeural|晓晓,zh-CN-YunxiNeural|云希"
                    ),
                ),
                ("searxng_base_url", models.URLField(default="http://127.0.0.1:8080")),
                (
                    "crawl4ai_base_url",
                    models.URLField(default="http://127.0.0.1:11235"),
                ),
                (
                    "supplement_relevance_threshold",
                    models.FloatField(
                        default=0.8,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "default_site_theme",
                    models.CharField(
                        choices=[
                            ("paper", "纯白"),
                            ("sepia", "暖黄"),
                            ("green", "护眼绿"),
                            ("gray", "柔灰"),
                            ("dark", "深黑"),
                            ("midnight", "夜蓝"),
                            ("charcoal", "炭灰"),
                            ("coffee", "暖黑"),
                        ],
                        default="paper",
                        max_length=20,
                    ),
                ),
                (
                    "default_reader_font",
                    models.CharField(
                        choices=[
                            ("system", "系统字体"),
                            ("song", "宋体"),
                            ("kai", "楷体"),
                            ("serif", "衬线字体"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                (
                    "api_timeout_ms",
                    models.PositiveIntegerField(
                        default=10000,
                        validators=[django.core.validators.MinValueValidator(1000)],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "系统配置",
                "verbose_name_plural": "系统配置",
            },
        ),
    ]
