# Generated by Django 4.2.30 on 2026-08-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0030_systemconfiguration"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="aitask",
            index=models.Index(
                fields=[
                    "trigger_type",
                    "trigger_id",
                    "task_type",
                    "-created_at",
                    "status",
                ],
                name="task_trigger_lookup_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aitask",
            index=models.Index(
                fields=["status", "-priority", "next_run_at", "id"],
                name="task_status_due_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aitask",
            index=models.Index(
                fields=["status", "task_type", "-created_at"],
                name="task_status_type_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="concept",
            index=models.Index(
                fields=["topic", "-updated_at"], name="concept_topic_updated_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["topic", "-created_at"], name="exam_topic_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewrecord",
            index=models.Index(
                fields=["result", "due_at"], name="review_result_due_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["-updated_at"], name="session_updated_idx"),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(fields=["-updated_at"], name="topic_updated_idx"),
        ),
        migrations.AddIndex(
            model_name="topicmaterial",
            index=models.Index(
                condition=models.Q(("removed_at__isnull", True)),
                fields=["topic", "material"],
                name="topicmat_active_topic_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="topicmaterial",
            index=models.Index(
                condition=models.Q(("removed_at__isnull", True)),
                fields=["material", "topic"],
                name="topicmat_active_mat_idx",
            ),
        ),
    ]
