# Generated by Django 4.2.30 on 2026-08-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0031_aitask_task_trigger_lookup_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("usability", "不好用"),
                            ("bug", "功能异常"),
                            ("content", "内容问题"),
                            ("suggestion", "功能建议"),
                            ("other", "其他"),
                        ],
                        db_index=True,
                        default="usability",
                        max_length=20,
                        verbose_name="反馈类型",
                    ),
                ),
                ("description", models.TextField(verbose_name="反馈内容")),
                (
                    "page_url",
                    models.CharField(
                        blank=True, max_length=2000, verbose_name="页面地址"
                    ),
                ),
                (
                    "page_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="页面标题"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="浏览器信息")),
                (
                    "context",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="页面上下文"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "待处理"),
                            ("reviewing", "处理中"),
                            ("resolved", "已解决"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "resolution_note",
                    models.TextField(blank=True, verbose_name="处理记录"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "使用反馈",
                "verbose_name_plural": "使用反馈",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="feedback_status_created_idx",
                    ),
                    models.Index(
                        fields=["category", "-created_at"],
                        name="feedback_category_created_idx",
                    ),
                ],
            },
        ),
    ]
