# Generated by Django 4.2.30 on 2026-08-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0032_userfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfiguration",
            name="llm_model_management_assistant",
            field=models.CharField(default="qwen3:30b-a3b", max_length=100),
        ),
    ]
