# Generated by Django 4.2.30 on 2026-08-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0033_systemconfiguration_llm_model_management_assistant"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={
                "ordering": ["-is_pinned", "-updated_at"],
                "verbose_name": "学习主题",
                "verbose_name_plural": "学习主题",
            },
        ),
        migrations.AddField(
            model_name="topic",
            name="is_pinned",
            field=models.BooleanField(default=False, verbose_name="是否置顶"),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                fields=["-is_pinned", "-updated_at"], name="topic_pinned_updated_idx"
            ),
        ),
    ]
