# Generated by Django 4.2.30 on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0034_alter_topic_options_topic_is_pinned_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfeedback",
            name="feature",
            field=models.CharField(
                choices=[
                    ("management_assistant", "全站管理助手"),
                    ("topic_management", "话题管理"),
                    ("topic_detail", "话题详情"),
                    ("material_reader", "学习阅读"),
                    ("material_management", "材料管理"),
                    ("exam", "掌握度评估"),
                    ("review", "复习计划"),
                    ("task_management", "任务管理"),
                    ("system_settings", "系统设置"),
                    ("feedback", "反馈功能"),
                    ("other", "其他"),
                ],
                db_index=True,
                default="other",
                max_length=30,
                verbose_name="所属功能",
            ),
        ),
        migrations.AddIndex(
            model_name="userfeedback",
            index=models.Index(
                fields=["feature", "-created_at"],
                name="feedback_feature_created_idx",
            ),
        ),
    ]
