# Generated by Django 4.2.30 on 2026-08-08 15:25

import django.core.validators
from django.db import migrations, models


def raise_existing_relevance_threshold(apps, schema_editor):
    configuration = apps.get_model("api", "SystemConfiguration")
    configuration.objects.filter(supplement_relevance_threshold__lt=0.85).update(
        supplement_relevance_threshold=0.85
    )


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0035_userfeedback_feature"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfiguration",
            name="default_speech_rate",
            field=models.FloatField(
                default=1.5,
                validators=[
                    django.core.validators.MinValueValidator(0.5),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AddField(
            model_name="systemconfiguration",
            name="default_tts_voice",
            field=models.CharField(default="zh-CN-YunxiNeural", max_length=100),
        ),
        migrations.AddField(
            model_name="systemconfiguration",
            name="supplement_excluded_domains",
            field=models.TextField(default="wikipedia.org"),
        ),
        migrations.AlterField(
            model_name="systemconfiguration",
            name="supplement_relevance_threshold",
            field=models.FloatField(
                default=0.85,
                validators=[
                    django.core.validators.MinValueValidator(0.85),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.RunPython(
            raise_existing_relevance_threshold,
            migrations.RunPython.noop,
        ),
    ]
