# Generated by Django 4.2.30 on 2026-08-08 15:46

import django.core.validators
from django.db import migrations, models


def copy_defaults_to_current_preferences(apps, schema_editor):
    configuration = apps.get_model("api", "SystemConfiguration")
    for item in configuration.objects.all():
        item.current_site_theme = item.default_site_theme
        item.current_reader_font = item.default_reader_font
        item.current_tts_voice = item.default_tts_voice
        item.current_speech_rate = item.default_speech_rate
        item.save(
            update_fields=[
                "current_site_theme",
                "current_reader_font",
                "current_tts_voice",
                "current_speech_rate",
            ]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0036_systemconfiguration_default_speech_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfiguration",
            name="current_reader_font",
            field=models.CharField(
                choices=[
                    ("system", "系统字体"),
                    ("song", "宋体"),
                    ("kai", "楷体"),
                    ("serif", "衬线字体"),
                ],
                default="system",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="systemconfiguration",
            name="current_site_theme",
            field=models.CharField(
                choices=[
                    ("paper", "纯白"),
                    ("sepia", "暖黄"),
                    ("green", "护眼绿"),
                    ("gray", "柔灰"),
                    ("dark", "深黑"),
                    ("midnight", "夜蓝"),
                    ("charcoal", "炭灰"),
                    ("coffee", "暖黑"),
                ],
                default="paper",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="systemconfiguration",
            name="current_speech_rate",
            field=models.FloatField(
                default=1.5,
                validators=[
                    django.core.validators.MinValueValidator(0.5),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AddField(
            model_name="systemconfiguration",
            name="current_tts_voice",
            field=models.CharField(default="zh-CN-YunxiNeural", max_length=100),
        ),
        migrations.RunPython(
            copy_defaults_to_current_preferences,
            migrations.RunPython.noop,
        ),
    ]
