# Generated by Django 4.2.30 on 2026-08-10 07:30

from django.db import migrations, models


def add_book_platform_domains(apps, schema_editor):
    configuration = apps.get_model("api", "SystemConfiguration")
    for item in configuration.objects.all():
        domains = [
            domain.strip()
            for domain in item.supplement_excluded_domains.split(",")
            if domain.strip()
        ]
        for required_domain in ("weread.qq.com", "douban.com"):
            if required_domain not in domains:
                domains.append(required_domain)
        item.supplement_excluded_domains = ",".join(domains)
        item.save(update_fields=["supplement_excluded_domains"])


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0037_systemconfiguration_current_reader_font_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemconfiguration",
            name="supplement_excluded_domains",
            field=models.TextField(default="wikipedia.org,weread.qq.com,douban.com"),
        ),
        migrations.RunPython(add_book_platform_domains, migrations.RunPython.noop),
    ]
