# Generated by Django 4.2.30 on 2026-08-10 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0038_expand_supplement_excluded_domains"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="标题"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, default="", verbose_name="Markdown 正文"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_drafts",
                        to="api.topic",
                        verbose_name="所属主题",
                    ),
                ),
            ],
            options={
                "verbose_name": "材料草稿",
                "verbose_name_plural": "材料草稿",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["topic", "-updated_at"], name="draft_topic_updated_idx"
                    )
                ],
            },
        ),
    ]
