# Generated by Django 4.2.30 on 2026-08-10 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0039_material_drafts"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialDraftVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField(verbose_name="版本号")),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="标题"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, default="", verbose_name="Markdown 正文"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="api.materialdraft",
                        verbose_name="所属草稿",
                    ),
                ),
            ],
            options={
                "verbose_name": "材料草稿历史版本",
                "verbose_name_plural": "材料草稿历史版本",
                "ordering": ["-version_number"],
                "indexes": [
                    models.Index(
                        fields=["draft", "-version_number"],
                        name="draft_version_number_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="materialdraftversion",
            constraint=models.UniqueConstraint(
                fields=("draft", "version_number"), name="unique_draft_version"
            ),
        ),
    ]
