# Generated by Django 4.2.30 on 2026-08-15 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0041_harden_locator_ownership"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapturedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="标题")),
                (
                    "source_url",
                    models.URLField(
                        blank=True, max_length=2000, verbose_name="来源地址"
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="站点名称"
                    ),
                ),
                (
                    "adapter",
                    models.CharField(max_length=100, verbose_name="采集适配器"),
                ),
                (
                    "snapshot_json",
                    models.JSONField(default=dict, verbose_name="文档快照"),
                ),
                (
                    "markdown",
                    models.TextField(
                        blank=True, default="", verbose_name="Markdown 正文"
                    ),
                ),
                (
                    "asset_manifest",
                    models.JSONField(blank=True, default=list, verbose_name="资源清单"),
                ),
                (
                    "warnings",
                    models.JSONField(blank=True, default=list, verbose_name="采集告警"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("receiving", "接收中"),
                            ("ready", "待整理"),
                            ("imported", "已导入"),
                            ("failed", "失败"),
                        ],
                        db_index=True,
                        default="receiving",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "draft",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_capture",
                        to="api.materialdraft",
                        verbose_name="生成的草稿",
                    ),
                ),
                (
                    "material",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_capture",
                        to="api.material",
                        verbose_name="导入的材料",
                    ),
                ),
            ],
            options={
                "verbose_name": "浏览器采集",
                "verbose_name_plural": "浏览器采集",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="capture_status_created_idx",
                    )
                ],
            },
        ),
    ]
